# app/api/setup.py
# Token-gated initial setup (setup wizard).
#
# The SETUP_TOKEN is generated by the installer and written to /opt/pastegate/SETUP_TOKEN.
# As long as this (non-empty) file exists, setup mode is open:
#   - GET  /status        reports needs_setup + has_admin
#   - POST /verify-token  checks the token in constant time
#   - POST /create-admin  creates the first admin (only if no admin exists yet)
#   - POST /init-totp     creates a TOTP secret for the admin (QR via otpauth URI)
#   - POST /confirm-totp  enables 2FA
#   - POST /init-apikey   creates the first API key (cleartext returned ONCE)
#   - POST /settings      sets organisation-wide settings (default_lang)
#   - POST /complete      finishes setup and removes the token best-effort
#
# Robustness: needs_setup is (token open AND no active admin yet). As soon as an
# admin exists, the frontend locks reliably — even if the token file cannot be
# removed (e.g. due to directory permissions). complete() removes/empties the
# token best-effort and NO LONGER fails with a 500.
#
# Reuses the existing auth/key/TOTP helpers. No schema change.

import hmac
import os

import pyotp
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.app_settings import set_default_lang
from app.core.database import get_db
from app.core.i18n import LANG_PATTERN, _
from app.core.qr import totp_qr_data_uri
from app.core.security import generate_api_key, hash_api_key, hash_password
from app.models.models import ApiKey, User, UserRole

router = APIRouter(prefix='/api/v1/setup', tags=['setup'])

# Candidate paths for the token file (native + container) – overridable via env.
_TOKEN_CANDIDATES = [
    os.environ.get('SETUP_TOKEN_PATH', ''),
    '/opt/pastegate/SETUP_TOKEN',
    '/app/SETUP_TOKEN',
    os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'SETUP_TOKEN'),
]


def _token_path() -> str | None:
    for p in _TOKEN_CANDIDATES:
        if p and os.path.isfile(p):
            return p
    return None


def _read_token() -> str | None:
    p = _token_path()
    if not p:
        return None
    try:
        with open(p, 'r', encoding='utf-8') as f:
            return f.read().strip()
    except OSError:
        return None


def _setup_open() -> bool:
    """Setup mode is open as long as a (non-empty) token file exists."""
    return bool(_read_token())


def _clear_token() -> bool:
    """Make the token unusable, best-effort: delete it first, otherwise empty it.
    Returns True if the token is gone/empty afterwards, else False."""
    p = _token_path()
    if not p:
        return True
    try:
        os.remove(p)
        return True
    except OSError:
        pass
    try:
        with open(p, 'w', encoding='utf-8') as f:
            f.write('')
        return True
    except OSError:
        return False


def _active_admin(db: Session) -> User | None:
    return db.scalar(
        select(User).where(User.role == UserRole.admin, User.is_active == True)  # noqa: E712
        .order_by(User.created_at)
    )


def _admin_exists(db: Session) -> bool:
    """True as soon as an admin has EVER been created (active or deactivated).
    Guard against setup reactivation: if the only admin is later deactivated
    and the token file was not deleted, /setup must NOT be able to create
    another admin."""
    return db.scalar(
        select(User).where(User.role == UserRole.admin).limit(1)
    ) is not None


def _require_token(provided: str, db: Session) -> None:
    """Constant-time comparison + setup-open check. Raises 403/401 on failure."""
    if not _setup_open():
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=_('setup.already_completed'))
    real = _read_token() or ''
    if not provided or not hmac.compare_digest(provided, real):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail=_('setup.invalid_token'))


# ── Schemas ───────────────────────────────────────────────────────

class TokenBody(BaseModel):
    token: str = Field(min_length=1, max_length=256)


class CreateAdminBody(TokenBody):
    username: str = Field(min_length=2, max_length=64)
    email:    str = Field(min_length=3, max_length=256)
    password: str = Field(min_length=12, max_length=256)


class ConfirmTotpBody(TokenBody):
    totp_code: str = Field(min_length=6, max_length=6)


class InitApiKeyBody(TokenBody):
    name: str = Field(default='Extension – Rollout', min_length=1, max_length=128)


class SettingsBody(TokenBody):
    default_lang: str = Field(pattern=LANG_PATTERN)


# ── Endpoints ─────────────────────────────────────────────────────

@router.get('/status')
def status_(db: Session = Depends(get_db)):
    """Public. Drives the frontend gate (/setup redirect).
    needs_setup is only true while setup is open AND there is no active admin yet —
    so the frontend locks even if the token file cannot be removed."""
    has_admin = _admin_exists(db)
    return {
        'needs_setup': _setup_open() and not has_admin,
        'has_admin':   has_admin,
    }


@router.post('/verify-token')
def verify_token(body: TokenBody, db: Session = Depends(get_db)):
    _require_token(body.token, db)
    return {'valid': True, 'has_admin': _active_admin(db) is not None}


@router.post('/create-admin', status_code=status.HTTP_201_CREATED)
def create_admin(body: CreateAdminBody, db: Session = Depends(get_db)):
    _require_token(body.token, db)
    if _admin_exists(db):
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=_('setup.admin_exists'))
    if db.scalar(select(User).where(User.username == body.username)):
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=_('users.username_taken'))

    user = User(
        username=body.username,
        email=body.email,
        password_hash=hash_password(body.password),
        role=UserRole.admin,
        is_active=True,
    )
    db.add(user)
    db.commit()
    return {'id': str(user.id), 'username': user.username, 'role': user.role.value}


@router.post('/init-totp')
def init_totp(body: TokenBody, db: Session = Depends(get_db)):
    """Create a TOTP secret for the admin. The frontend renders the QR code from qr_uri."""
    _require_token(body.token, db)
    admin = _active_admin(db)
    if not admin:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=_('setup.no_admin'))
    secret = pyotp.random_base32()
    qr_uri = pyotp.TOTP(secret).provisioning_uri(name=admin.email, issuer_name='Pastegate')
    admin.totp_secret  = secret
    admin.totp_enabled = False
    db.commit()
    return {'secret': secret, 'qr_uri': qr_uri, 'qr_image': totp_qr_data_uri(qr_uri)}


@router.post('/confirm-totp')
def confirm_totp(body: ConfirmTotpBody, db: Session = Depends(get_db)):
    _require_token(body.token, db)
    admin = _active_admin(db)
    if not admin or not admin.totp_secret:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=_('auth.totp_no_secret'))
    if not pyotp.TOTP(admin.totp_secret).verify(body.totp_code, valid_window=1):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=_('auth.totp_invalid'))
    admin.totp_enabled = True
    db.commit()
    return {'totp_enabled': True}


@router.post('/init-apikey', status_code=status.HTTP_201_CREATED)
def init_apikey(body: InitApiKeyBody, db: Session = Depends(get_db)):
    """Create the first API key. The cleartext is returned ONCE (DB: HMAC hash only)."""
    _require_token(body.token, db)
    admin = _active_admin(db)
    if not admin:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=_('setup.no_admin'))
    raw = generate_api_key()
    db.add(ApiKey(user_id=admin.id, name=body.name, key_hash=hash_api_key(raw), is_active=True))
    db.commit()
    return {'key': raw}


@router.post('/settings')
def save_settings(body: SettingsBody, db: Session = Depends(get_db)):
    _require_token(body.token, db)
    set_default_lang(db, body.default_lang)
    db.commit()
    return {'default_lang': body.default_lang}


@router.post('/complete')
def complete(body: TokenBody, db: Session = Depends(get_db)):
    """Finish setup. Removes/empties the token best-effort. Does not fail if the
    file cannot be removed — needs_setup is then already false because an admin
    exists, so /setup stays locked."""
    _require_token(body.token, db)
    if _active_admin(db) is None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=_('setup.cannot_complete'))
    cleared = _clear_token()
    return {'ok': True, 'token_cleared': cleared}
